ui: 'bdd'
timeout: 0
full-trace: true
color: true
inline-diffs: true
allow-uncaught: true
async-only: true
parallel: true
jobs: 5
reporter: mochawesome
reporter-option:
  - 'reportPageTitle=Rush Wallet Test Report'
  - 'reportTitle=Rush Wallet Test Report'
  - 'code=false'
  - 'charts=true'
require:
  - mochawesome/register
