on:
  push:
  pull_request:
    branches:
      - dev

name: Build test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build project
        uses: actions/setup-node@v2-beta
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          args: install
      - uses: actions/cache@v1
        env:
          node-version: 12
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-node${{ env.node-version }}

      - name: Get Current Tag
        id: get_current_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      - name: Get Previous tag
        id: previous_tag
        run: echo ::set-output name=tag::$(git tag --sort v:refname | tail -n 2 | head -n 1)

      - name: Get next version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1.0
        with:
          version: ${{ steps.previous_tag.outputs.tag }}

      - name: Set development manifest
        if: steps.semvers.outputs.v_patch == steps.get_current_tag.outputs.tag
        run: |
            jq --argjson icons "{\"16\": \"icons/dev/16x16.png\",\"48\": \"icons/dev/48x48.png\",\"128\": \"icons/dev/128x128.png\"}" '.icons = $icons | .browser_action.default_icon = $icons | .name = "Liquality Wallet - Dev"' ./src/manifest.json > ./src/manifest.tmp
            mv ./src/manifest.tmp ./src/manifest.json
      - name: Set development agents
        if: steps.semvers.outputs.v_patch == steps.get_current_tag.outputs.tag
        run: |
            sed -i "s/\/swap-testnet\/agent/\/swap-testnet-dev\/agent/g; s/\/swap\/agent/\/swap-dev\/agent/g" src/build.config.js
      - run: |
          npm ci
          npm run lint
          npm run build

      - name: ===>> TestNet integration tests ==>>>
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          SEED_WORDS: ${{ secrets.TEST_NET_SEED_WORDS }}
        with:
          args: npm run test:testNetNetwork

